name: animated_gesture_detector
description: A package that allows u to create animated press/hold effect.
version: 1.0.0
homepage: https://github.com/KhudoliiAndrew/animated_gesture_detector.git

environment:
  sdk: '>=2.15.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
